### PR TITLE
Feature/nearby location

### LINKED ISSUE #45: Get nearby items based on Location
Get Location and query geohashes

### PR DESCRIPTION
**Pull request by PassiDel**
Closes #45 

TODO: Still waiting for LocationController (#53), but query is already working.
TODO: add better distance conversion (1.000m => 1km)

### CODE REVIEW

**Comment by PassiDel** [comment]
@everyone Should own items be hidden from the nearby page?

**Comment by frcroth** [comment]
> @ everyone Should own items be hidden from the nearby page?

Strongly in favor of hiding own items

**Review by AlexTerhar — APPROVED** [review]

**Comment by PassiDel** [comment]
> > @ everyone Should own items be hidden from the nearby page?
> 
> Strongly in favor of hiding own items

Small problem: the geoquery won't work with filtering the owner.
So either we filter on the client or just show it. Opinions?

**Comment by frcroth** [comment]
> > > @ everyone Should own items be hidden from the nearby page?
> > 
> > Strongly in favor of hiding own items
> 
> Small problem: the geoquery won't work with filtering the owner.
> So either we filter on the client or just show it. Opinions?

Filtering on the client sounds very good or are there problems associated with it?

**Comment by PassiDel** [comment]
> Filtering on the client sounds very good or are there problems associated with it?

Only the increased firestore read-usage and unnecessary network traffic, both negligible.

**Comment by PassiDel** [comment]
Closed because of rebasing.

**Pull request closed without merging**
